# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d8d9cd6d6bf94d16e17f79dc9646d3ac"
name = "checkoutUI"
handle = "checkoutui-40"
application_url = "https://sum-christine-ns-prisoners.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sum-christine-ns-prisoners.trycloudflare.com/auth/callback",
  "https://sum-christine-ns-prisoners.trycloudflare.com/auth/shopify/callback",
  "https://sum-christine-ns-prisoners.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[[extensions]]
name = "checkout-ui"
type = "checkout_ui_extension"
path = "extensions/checkout-ui"
